language: python

matrix:
  include:
  - name: linux
    python:
     - 3.6
     - 3.7

  - name: osx-py3.7
    os: osx
    osx_image: xcode11 # python 3.7 apparently
    language: shell
    #env: TOXENV=py3
    #addons:
    #   homebrew:
    #     update: true
    #     packages: python3
  - name: windows-py3.7
    os: windows
    language: shell
    before_install:
       - choco install python # python 3.7 apparently
       - python -m pip install --upgrade pip
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
#    install: pip3 install ipython-IDV
#    script:
#       - python
#       - python -c "import ipython_IDV"

# all languages should agree on these
install:
    - pip3 install ipywidgets 
    - pip3 install requests
    - pip3 install ipython-IDV
    - pip3 install ipyidv[addons] # addons also installs xarray and netcdf4

# on windows python3 is command not found
script:
    - python3 -c "from ipython_IDV import drilsdown" || python -c "from ipython_IDV import drilsdown"
    - ipython -c "from ipython_IDV import drilsdown"
    - ipython -c "%load_ext ipyidv"
