language: python
python:
  - 3.6
  - 3.7

matrix:
  include:
  - os: linux
    name: linux
    python: 3.7
    install: pip install ipython-IDV
    script:
    - python -c "import ipython_IDV"

  - os: osx
    name: osx
    language: minimal
    install: pip3 install ipython-IDV
    script:
    - python -c "print('hello')"
    - python -c "import ipython_IDV"

  - os: windows
    name: windows
    language: minimal
    before_install:
    - choco install python3
    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
    install: pip3 install ipython-IDV
    script:
    - python -c "import ipython_IDV"
