os:
  - linux
  - osx
language: python
python:
 - '3.6'
 - '3.7'
install:
# - sudo apt-get update -q
  - pip install ipython-IDV 
script:
  - python -c "import ipython_IDV"
  - ipython -c "%load_ext ipython_IDV"
  
