language: python

matrix:
  include:
  # default ubuntu x86_64 on travis
  - name: linux
    python:
     - 3.6
     - 3.7
  # osx 
  - name: osx-py3.7
    os: osx
    osx_image: xcode11 # python 3.7 apparently
    language: shell # python for osx not supported on travis
  # windows 10, i suppose
  - name: windows-py3.7
    os: windows
    language: shell # python for windows is not supported on travis
    before_install:
       - choco install python # python 3.7 apparently
       - python -m pip install --upgrade pip
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

# all operating systems should agree on these
install:
    - pip3 install ipywidgets 
    - pip3 install requests
    - pip3 install ipython-IDV
    - pip3 install ipyidv[addons] # addons also installs xarray and netcdf4

# on windows python3 is command not found
script:
    - python3 -c "from ipython_IDV import drilsdown" || python -c "from ipython_IDV import drilsdown"
    - ipython -c "%load_ext ipython_IDV.drilsdown"
    - ipython -c "from ipython_IDV import drilsdown"
    - ipython -c "%load_ext ipyidv"
    - pip3 uninstall ipywidgets requests ipython_IDV ipyidv -y
    - pip3 install drilsdown
    - ipython -c "%load_ext ipython_IDV.drilsdown"
